### ISSUE TITLE
Intersection tool doesn't work with QGIS2.8.1

### ISSUE THREAD

**Issue by DelazJ** [geopython/CadTools#17] opened 2015-03-13 09:29 UTC
Hi,
while trying to create point at intersection of two segment, selecting the first tool and then clicking on the line does nothing. The line doesn't become red as it does with QGIS2.4 (tried also this day). And after having clicked on the two lines (though nothing is shown as selected), when you try to create the point, got message "Not enough line segments selected", confirming that no line has been selected.
Tried arc intersection with success on same layer...

**Comment by kalxas** [comment] 2015-03-14 15:24
I haven't tested it with 2.8 yet.

**Comment by kalxas** [comment] 2015-06-02 18:44
Duplicate of https://github.com/geopython/CadTools/issues/18
Snapping API changed in 2.8.x

**Closed** 2015-06-02 18:44 UTC
Labels: duplicate
